@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User as U
participant Client as C
queue "In Messages" as CQ
entity Broker as B
queue "All Messages" as SQ
participant Server as S
Database Database as D

U --> C : Visitor signs in
C --> B : Publish IN message
activate B
B --> CQ : Deliver IN message
autonumber 3
B --> SQ : Deliver IN message
deactivate B
loop 
C --> CQ : Check for messages
CQ --> C : Deliver messages
C --> C : Parse messages
end loop
autonumber 4
loop
SQ <-- S : Check for messages
S <-- SQ : Deliver messages
S --> S : Parse messages
S --> D : Persist messages
end loop


@enduml